/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.client;
import java.io.*;
import java.net.*;
import javax.swing.JOptionPane;
/**
 *
 * @author mustafa
 */
public class Client extends javax.swing.JFrame {

    static Socket socket = null;
    static DataInputStream Dins;
    static DataOutputStream Dops;
    static int port = 3333;
    static InetAddress inetAddress;
    static InetSocketAddress inetSocketAddress;
    static int say = 1;
    static String output="";
    
    
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        TextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setResizable(false);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jButton1.setText("Gönder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String veri = "",son = "",temp = "";
        
        if("".equals(veri = TextField.getText())){
            return;
        }        
        
        TextField.setText("");        
        
        if(Yabanci_kar_sor(veri)){
            JOptionPane.showMessageDialog(null, "Lütfen yanlızca türkçe karakter kullanınız");
            return;
        }
        
        Encryption enc = new Encryption();
        
        if(Create_Client.Cesar_Temp){
            son = enc.EncryptCesar(veri, Create_Client.Cesar_Code);
            output +=veri + " Metninin "+Create_Client.Cesar_Code+" Karakter Cezarlı Şifresi :"+son+"\n";
            veri = son;
        }
        if(Create_Client.Vigenere_Temp){
            temp = Create_Client.Vigenere_Code_String.replace(" ", "");
            if(veri.replace(" ", "").length() != temp.length()){
                JOptionPane.showMessageDialog(null, "Metinlerin uzunlukları eşit değildir lütfen Anahtar ile eşit büyüklükte metin giriniz.");
                return;
           }
           son = enc.EncryptVigenere(veri, temp);
           output += veri + " Metninin Vigenere Şifresi :"+son+"\n";
           veri = son;
        }
        if(Create_Client.Sutun_Temp){
            son=enc.EncryptColumn(veri);
            output += veri + " Metninin Column Şifresi :"+son+"\n";
            veri=son;
            
        }if(Create_Client.Cit_Temp){
            son= enc.EncryptCIT(veri);
            output += veri + " Metninin Cit Şifresi :"+son+"\n";
            veri=son;
        }
        if(Create_Client.Polybiusv_Temp){
            son = enc.EncryptPolybius(veri);
            output+=veri + " Metninin Polybius Şifresi :"+son;
            veri = son;
        }
        System.out.println(output+"\n\n\n");
        output = "";
        try {
                Dops.writeUTF(Create_Client.Username_text+":" + veri);
            } catch (IOException ex) {
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Client().setVisible(true);
            }
        });
        int port = 3333;
        String son = "",temp = "";
        String[] temp2;
        Encryption enc = new Encryption();
        inetAddress = InetAddress.getByName("127.0.0.1");
        inetSocketAddress = new InetSocketAddress(inetAddress,port);
        try {
            socket = new Socket();
            socket.connect(inetSocketAddress);
            System.out.println("Bağlandı");
        } catch (Exception e) {
            System.out.println("bağlanamadı");
        }
        Dins = new DataInputStream(socket.getInputStream());
        Dops = new DataOutputStream(socket.getOutputStream());
        String veri="";
        while(true){
            veri=Dins.readUTF();
            temp2 = veri.split(":");
            veri = temp2[1];
        
            if(Create_Client.Polybiusv_Temp){
                son = enc.DecryptionPolybius(veri);
                output +=veri + " Metninin Polybius Deşifresi:"+son+"\n";
                veri = son;
            }
            if(Create_Client.Cit_Temp){
               son = enc.DecryptionCIT(veri);
               output += veri + " Metninin Cit Deşifresi:"+son+"\n";
               veri = son;
            }
            if(Create_Client.Sutun_Temp){
                son= enc.DecryptionColumn(veri);
                output += veri + " Metninin Sutun Desifresi:"+son+"\n";
                veri=son;
            }if(Create_Client.Vigenere_Temp){
                son=enc.DecryptionVigenere(veri,Create_Client.Vigenere_Code_String);
                output += veri + " Metninin Vigenere Deşifresi :"+son+"\n";
                veri=son;
            }
            if(Create_Client.Cesar_Temp){
                son = enc.DecryptionCesar(veri,Create_Client.Cesar_Code);
                output+=veri + " Metninin Cesar Deifresi :"+son;
                veri = son;
            }
            System.out.println(output);
            output = "";
            TextArea.append(temp2[0] + " --> " +veri+"\n");
        }
        
        
    }
    public static boolean Yabanci_kar_sor(String value){
        char[] alfabe = {'A','B','C','Ç','D','E','F','G','Ğ','H','I','İ','J','K','L','M','N','O','Ö','P','R','S','Ş','T','U','Ü','V','Y','Z'};
        int sayac;
        value = value.toUpperCase();
        value = value.replace(" ", "");
        for(char var : value.toCharArray()){
            sayac = 0;
            for(char var2 : alfabe){
                if(var == var2)
                    sayac++;
            }
            if(sayac == 0)
                return true;
        }
        return false;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
