/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.client;

import javax.swing.JOptionPane;

/**
 *
 * @author mustafa
 */
public class Create_Client extends javax.swing.JFrame {

    int say = 1,say2 = 1;
    public static boolean Cesar_Temp=false,Vigenere_Temp=false,Polybiusv_Temp=false,Cit_Temp=false,Sutun_Temp=false;
    public static String Vigenere_Code_String="",Username_text="";
    public static int Cesar_Code;
    /**
     * Creates new form Create_Client
     */
    public Create_Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sütun = new javax.swing.JCheckBox();
        CesarCount = new javax.swing.JTextField();
        Cesar = new javax.swing.JCheckBox();
        Polybius = new javax.swing.JCheckBox();
        Vigenere = new javax.swing.JCheckBox();
        Çit = new javax.swing.JCheckBox();
        Vigenere_Code = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sütun.setText("Sütun");

        CesarCount.setEnabled(false);

        Cesar.setText("Cesar");
        Cesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CesarActionPerformed(evt);
            }
        });

        Polybius.setText("Polybius");

        Vigenere.setText("Vigenere");
        Vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VigenereActionPerformed(evt);
            }
        });

        Çit.setText("Çit");

        Vigenere_Code.setEnabled(false);

        jLabel1.setText("Kullanıcı Adı:");

        jButton1.setText("BAĞLAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Cesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sütun)
                        .addGap(60, 60, 60)
                        .addComponent(Çit)
                        .addGap(37, 37, 37)
                        .addComponent(Polybius)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CesarCount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Vigenere)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Vigenere_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vigenere)
                    .addComponent(Vigenere_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cesar)
                    .addComponent(CesarCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Çit)
                    .addComponent(Sütun)
                    .addComponent(Polybius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CesarActionPerformed
        if(say %2 == 1){
            CesarCount.setEnabled(true);
        }
        else{
            CesarCount.setEnabled(false);
        }
        say++;
    }//GEN-LAST:event_CesarActionPerformed

    private void VigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VigenereActionPerformed
        if(say2 %2 == 1){
            Vigenere_Code.setEnabled(true);
        }
        else{
            Vigenere_Code.setEnabled(false);
        }
        say2++;
    }//GEN-LAST:event_VigenereActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if("".equals(Username.getText())){
            JOptionPane.showMessageDialog(null, "Lütfen Bir Kullanıcı Adı Belirleyiniz");
            return;
        }
        if(Yabanci_kar_sor(Vigenere_Code.getText())){
            JOptionPane.showMessageDialog(null, "Lütfen yanlızca türkçe karakter kullanınız");
            return;
        }
        if(Vigenere.isSelected() && Sütun.isSelected()){
            JOptionPane.showMessageDialog(null, "Sütun şifreleme ile Vigenere şifreleme aynı anda kulllanılamaz");            
        }
        if(Cesar.isSelected()){
            Cesar_Temp = true;
            Cesar_Code = Integer.valueOf(CesarCount.getText());
        }
        if(Vigenere.isSelected()){
            Vigenere_Temp = true;
            Vigenere_Code_String = Vigenere_Code.getText();
        }
        if(Polybius.isSelected())
            Polybiusv_Temp = true;
        if(Çit.isSelected())
            Cit_Temp = true;
        if(Sütun.isSelected())
            Sutun_Temp = true;
       
       Username_text = Username.getText();
       Client client = new Client();
       client.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
    }
    
    
    
    public boolean Yabanci_kar_sor(String value){
        char[] alfabe = {'A','B','C','Ç','D','E','F','G','Ğ','H','I','İ','J','K','L','M','N','O','Ö','P','R','S','Ş','T','U','Ü','V','Y','Z'};
        int sayac;
        value = value.toUpperCase();
        value = value.replace(" ", "");
        for(char var : value.toCharArray()){
            sayac = 0;
            for(char var2 : alfabe){
                if(var == var2)
                    sayac++;
            }
            if(sayac == 0)
                return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Cesar;
    private javax.swing.JTextField CesarCount;
    private javax.swing.JCheckBox Polybius;
    private javax.swing.JCheckBox Sütun;
    public static javax.swing.JTextField Username;
    private javax.swing.JCheckBox Vigenere;
    private javax.swing.JTextField Vigenere_Code;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox Çit;
    // End of variables declaration//GEN-END:variables
}
